application: eveshoppinglist
version: 3
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "latest"

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /shoppinglist
  static_files: index.html
  upload: index.html

- url: /logaggregator
  static_files: inspector.html
  upload: inspector.html

- url: /inspector/.*
  script: redirector.app

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /app/.*
  script:  shoppinglist.app

- url: /ip/.*
  script:  iplookup.app
